server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/word_website?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        timezone: GMT+8
        serialization:
            write-dates-as-timestamps: false

mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.wordland.model

